### ISSUE TITLE
Predicting returns 500 Internal Server Error

### ISSUE THREAD

**Issue by jcklie** [inception-project/external-recommender-dkpro-tc#1]
When I run

`⇒  curl -H "Content-Type: application/json" --data @jsonPredictRequestV2small.txt http://localhost:30500/predict`

then the server replies with

`{"timestamp":1538040463710,"status":500,"error":"Internal Server Error","exception":"java.lang.NoClassDefFoundError","message":"org/dkpro/tc/features/ngram/base/LuceneFeatureExtractorBase","path":"/predict"}`

**Comment by Horsmann** [comment]
Ah. I changed a package path in the backend for the latest release. This leads now to this error because the class is now located elsewhere. 

This problem occurs for a model that was trained with `1.0.1` and now the version is set to `1.0.2` and the package path of the class has changed. This is fixable by re-train the model with the new version. Sorry. I didn't think of that when moving the class into another package.

**Comment by jcklie** [comment]
Works after deleting. Thank you!
